
name: Test Cases Modified
on:
  push:
    branches: main

jobs:
  TestCases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
      
      - name: Compile
        run: |
          cd $GITHUB_WORKSPACE/
          export CLASSPATH="./ojdbc8.jar:./"
          javac TestCasesModified.java
      
      - name: Execute
        run: |
          cd $GITHUB_WORKSPACE/
          export CLASSPATH="./ojdbc8.jar:./"
          echo "$env:LOGIN"
          java TestCasesModified ${{secrets.LOGIN}} ${{secrets.PASSWORD}}
         
