@startuml
title Usecase for Information system

' left to right direction

actor Користувач
actor :Програма для малювання:

Гість -|> Користувач 

rectangle Software {
  usecase (Обрати ПО для підключення)
  Користувач --> (Авторизувати користувача)
  (Створити свою підбірку) ..> (Авторизувати користувача) : <<include>>
  (Підключити підбірку до проекту) ..> (Авторизувати користувача) : <<include>>
  (Обрати ПО для підключення) .> (Підключити підбірку до проекту) : extends
  :Програма для малювання: -- (Обрати ПО для підключення)

}
@enduml
